=== Pouet-Coding/JAXBProject/target/classes/lasergame/lasergame.xsd
<?xml version="1.0" encoding="UTF-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/lasergame"
	xmlns:tns="http://www.example.org/lasergame" elementFormDefault="qualified">

	<element name="Partie">
		<complexType>
			<sequence>
				<element name="numeroPartie" type="int"></element>
				<element name="libellePartie" type="string"></element>
				<element name="Joueurs" type="tns:Joueur" maxOccurs="unbounded"></element>
				<element name="Scores" type="tns:Score"></element>
			</sequence>
		</complexType>
	</element>

	<complexType name="Joueur">
		<sequence>
			<element name="numeroJoueur" type="int"></element>
			<element name="pseudo" type="string"></element>
			<element name="couleur" type="string"></element>
			<element name="score" type="tns:Score"></element>
		</sequence>
	</complexType>

	<complexType name="Score">
		<sequence>
			<element name="numeroScore" type="int"></element>
			<element name="nbreMorts" type="int"></element>
			<element name="nbreTues" type="int"></element>
			<element name="handicap" type="double"></element>
		</sequence>
	</complexType>
</schema>

=== Pouet-Coding/JAXBProject/ressources/lasergame/lasergame.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Partie xmlns:tns="http://www.example.org/lasergame"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/lasergame lasergame.xsd ">

	<tns:numeroPartie>0</tns:numeroPartie>
	<tns:libellePartie>Poutrage professeurs affili√©s</tns:libellePartie>

	<tns:Joueurs>
		<tns:numeroJoueur>0</tns:numeroJoueur>
		<tns:pseudo>Pouet-Coding</tns:pseudo>
		<tns:couleur>ROUGE</tns:couleur>
		<tns:score>
			<tns:numeroScore>10000</tns:numeroScore>
			<tns:nbreMorts>5</tns:nbreMorts>
			<tns:nbreTues>201</tns:nbreTues>
			<tns:handicap>0.0</tns:handicap>
		</tns:score>
	</tns:Joueurs>

	<tns:Joueurs>
		<tns:numeroJoueur>1</tns:numeroJoueur>
		<tns:pseudo>Professeur1</tns:pseudo>
		<tns:couleur>BLEU</tns:couleur>
		<tns:score>
			<tns:numeroScore>-1760</tns:numeroScore>
			<tns:nbreMorts>201</tns:nbreMorts>
			<tns:nbreTues>5</tns:nbreTues>
			<tns:handicap>0.0</tns:handicap>
		</tns:score>
	</tns:Joueurs>

	<tns:Scores>
		<tns:numeroScore>8240</tns:numeroScore>
		<tns:nbreMorts>206</tns:nbreMorts>
		<tns:nbreTues>206</tns:nbreTues>
		<tns:handicap>0.0</tns:handicap>
	</tns:Scores>

</tns:Partie>
